hostname: rancher.local
bootstrapPassword: admin123

ingress:
  tls:
    source: secret

replicas: 1

# Para evitar errores en versiones 1.25+ si usas Rancher < 2.7.5
global:
  cattle:
    psp:
      enabled: false
